version: '3.6'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: 2
